[project]
name = "db-test-scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "faker>=37.4.0",
    "loguru>=0.7.3",
    "pandas>=2.3.0",
    "psycopg2>=2.9.10",
]
